Update deploy-to.openshift-dev.yml

diff --git a/.github/workflows/deploy-to.openshift-dev.yml b/.github/workflows/deploy-to.openshift-dev.yml
--- a/.github/workflows/deploy-to.openshift-dev.yml
+++ b/.github/workflows/deploy-to.openshift-dev.yml
@@ -88,28 +88,28 @@ jobs:
             }
       - name: Check out repository
         uses: actions/checkout@v3
+
 		
-	  - name: Get Image Tag
-	    id: get-image-hash
+      - name: Get Image Tag
+        id: get-image-hash
         uses: actions/checkout@v3
-		run: |
-		  IMAGE_NAME ='${{ env.APP_NAME_FRONTEND }}'
-		  TAG= '${{ env.TAG }}'
-		  IMAGE_HASH = $(oc get istag "${IMAGE_NAME}:${TAG}" -o template --template = '{{.image.dockerImageREference}}' | awk -F'@' '{print $2}')
-		  echo "IMAGE_HASH=${IMAGE_HASH}" >> $GITHUB_ENV
-		  echo "Image hash retrieved: ${IMAGE_HASH}"
+        run: |
+          IMAGE_NAME ='${{ env.APP_NAME_FRONTEND }}'
+          TAG= '${{ env.TAG }}'
+          IMAGE_HASH = $(oc get istag "${IMAGE_NAME}:${TAG}" -o template --template = '{{.image.dockerImageREference}}' | awk -F'@' '{print $2}')
+          echo "IMAGE_HASH=${IMAGE_HASH}" >> $GITHUB_ENV
+          echo "Image hash retrieved: ${IMAGE_HASH}"
 		  
-	- name: TAG Image
-	    id: tag_image
+      - name: TAG Image
+        id: tag_image
         uses: actions/checkout@v3
-		run: |
-		  IMAGE_NAME ='${{ env.APP_NAME_FRONTEND }}'
-		  TAG= '${{ env.TAG }}'
-		  
-		  IMAGE_HASH='${{ env.IMAGE_HASH }}'
-		  oc tag "${IMAGE_NAME}@${IMAGE_HASH}" "${IMAGE_NAME}:${TAG}" || echo "failed to tag the image"
-		  TAGGED_IMAGE= "${IMAGE_NAME}:${TAG}"
-		  echo "TAGGED_IMAGE=${TAGGED_IMAGE}" >> $GITHUB_ENV
+        run: |
+          IMAGE_NAME ='${{ env.APP_NAME_FRONTEND }}'
+          TAG= '${{ env.TAG }}'
+          IMAGE_HASH='${{ env.IMAGE_HASH }}'
+          oc tag "${IMAGE_NAME}@${IMAGE_HASH}" "${IMAGE_NAME}:${TAG}" || echo "failed to tag the image"
+          TAGGED_IMAGE= "${IMAGE_NAME}:${TAG}"
+          echo "TAGGED_IMAGE=${TAGGED_IMAGE}" >> $GITHUB_ENV
 		  
 		
       - name: Login to Docker Hub
