Update deploy-to.openshift-dev.yml

diff --git a/.github/workflows/deploy-to.openshift-dev.yml b/.github/workflows/deploy-to.openshift-dev.yml
--- a/.github/workflows/deploy-to.openshift-dev.yml
+++ b/.github/workflows/deploy-to.openshift-dev.yml
@@ -15,7 +15,6 @@ env:
   APP_NAME: ecas
   REPO_NAME: educ-ecas
   BRANCH: test_github_actions
- 
   APP_NAME_FRONTEND: ecas-frontend
   NAMESPACE: '${{ secrets.ECAS_NAMESPACE_NO_ENV }}'
   NAMESPACE_TOOLS: '${{ secrets.ECAS_NAMESPACE_NO_ENV }}-tools'
@@ -91,23 +90,19 @@ jobs:
       - name: Get Image Tag
         id: get-image-hash
         run: >
-          IMAGE_NAME ='${{ env.APP_NAME_FRONTEND }}'
-          TAG= '${{ env.TAG }}'
-          IMAGE_HASH = $(oc get istag "${IMAGE_NAME}:${TAG}" -o template --template = '{{.image.dockerImageREference}}' | awk -F'@' '{print $2}')
-          echo "IMAGE_HASH=${IMAGE_HASH}" >> $GITHUB_ENV
-          echo "Image hash retrieved: ${IMAGE_HASH}"
-		  
+          IMAGE_NAME ='${{ env.APP_NAME_FRONTEND }}' TAG= '${{ env.TAG }}'
+          IMAGE_HASH = $(oc get istag "${IMAGE_NAME}:${TAG}" -o template
+          --template = '{{.image.dockerImageREference}}' | awk -F'@' '{print
+          $2}') echo "IMAGE_HASH=${IMAGE_HASH}" >> $GITHUB_ENV echo "Image hash
+          retrieved: ${IMAGE_HASH}"
       - name: TAG Image
         id: tag_image
         run: >
-          IMAGE_NAME ='${{ env.APP_NAME_FRONTEND }}'
-          TAG= '${{ env.TAG }}'
-          IMAGE_HASH='${{ env.IMAGE_HASH }}'
-          oc tag "${IMAGE_NAME}@${IMAGE_HASH}" "${IMAGE_NAME}:${TAG}" || echo "failed to tag the image"
-          TAGGED_IMAGE= "${IMAGE_NAME}:${TAG}"
-          echo "TAGGED_IMAGE=${TAGGED_IMAGE}" >> $GITHUB_ENV
-		  
-		
+          IMAGE_NAME ='${{ env.APP_NAME_FRONTEND }}' TAG= '${{ env.TAG }}'
+          IMAGE_HASH='${{ env.IMAGE_HASH }}' oc tag
+          "${IMAGE_NAME}@${IMAGE_HASH}" "${IMAGE_NAME}:${TAG}" || echo "failed
+          to tag the image" TAGGED_IMAGE= "${IMAGE_NAME}:${TAG}" echo
+          "TAGGED_IMAGE=${TAGGED_IMAGE}" >> $GITHUB_ENV
       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
@@ -121,7 +116,6 @@ jobs:
           path_context: ./web-app
           builder_image: registry.redhat.io/rhscl/php-73-rhel7
           image: '${{ env.TAGGED_IMAGE }}'
-          #tags: latest
       - name: Push frontend to registry
         id: push-image-frontend
         uses: redhat-actions/push-to-registry@v2
